### ISSUE TITLE
can not select file

### ISSUE THREAD

**Issue by lukasz-virtualo** [emencia/emencia-django-slideshows#9]
There is no way for selecting the uploaded file. It is visible in the filebrowser but is not selectable. Clicking the name opens the file itself.
![screenshot from 2015-11-29 15 30 58](https://cloud.githubusercontent.com/assets/15977294/11458383/1fcc2016-96bf-11e5-9d1b-bc641abd875c.png)
Might have something in common with https://github.com/wardi/django-filebrowser-no-grappelli/issues/56
A possible fix is to copy the uploaded file URL, then clip the MEDIA_ROOT part and paste into the slide filename input field.

**Comment by sveetch** [comment]
Oops, i saw this bug but forgot to fix it, i'm working on it

**Comment by sveetch** [comment]
Well, i tested it again and remember how i resolved it, with disabling AdBlock Plus for my server hostname :) 

Don't know really why ABP is catching the version selector stuff, eventually a false positive.

All in all, this is not related to emencia-django-slideshows, you probably have enabled ABP / some Javascript blocker.
